/-
  Representational Regress — root import (scaffold; see `FORMALIZATION_MAP.md`).
-/

import RepresentationalRegress.Basic
import RepresentationalRegress.Regress
import RepresentationalRegress.FixedPoints
import RepresentationalRegress.Orientability
import RepresentationalRegress.Lawvere
import RepresentationalRegress.LawvereCCCType
import RepresentationalRegress.QuotientHausdorff
import RepresentationalRegress.CylinderMobius
import RepresentationalRegress.CylinderMobiusNonhomeo
import RepresentationalRegress.CylinderBoundary
import RepresentationalRegress.CylinderChartableBoundary
import RepresentationalRegress.MobiusCylinderBoundaryContrast
import RepresentationalRegress.PuncturedPlaneNotSimplyConnected
import RepresentationalRegress.HalfLineVsLine
import RepresentationalRegress.HalfPlaneVsPlane
import RepresentationalRegress.HalfSpaceNeighborVsPlane
import RepresentationalRegress.OpenCompactChartObstruction
import RepresentationalRegress.ChartableR2Neighbor
import RepresentationalRegress.ChartableR2Bridge
import RepresentationalRegress.ChartableR2Models
import RepresentationalRegress.MobiusChartableBoundary
import RepresentationalRegress.MobiusSeamChart
import RepresentationalRegress.MobiusSeamChartable
import RepresentationalRegress.MobiusSeamTrigInject
import RepresentationalRegress.MobiusSeamChartableR2
import RepresentationalRegress.Main

namespace RepresentationalRegress

/-- Root anchor for the library. -/
def programRoot : Unit := ()

end RepresentationalRegress
